### PR TITLE
Not ready to be merged..to be precise !!! ⚠️ 

### PR DESCRIPTION
**Pull request by Ndegwadavid**
I decided to use that branch solely because i think it might have some error issues especially in rendering the css from the static.

thus i used it for testing the django functionality of rendering CSS especially,,

Still not to be merged when fixed i will work on the master brach

### CODE REVIEW

**Comment by Ndegwadavid** [comment]
some weird python mange.py command i have used with help of gpt has really added thousands of files 😆 i never knew how to get along,,,,but this is generallly the over view look of it while running in developmentserver which i found it different while running on live server
Screenshot_2023-08-22_20_31_51
Screenshot_2023-08-22_20_31_54
 if you will not pull locally 
Screenshot_2023-08-22_20_31_44

**Comment by Denispeter** [comment]
Will check it out bro

**Comment by Ndegwadavid** [comment]
@Mu-Gee also not changed the db creds 🤣

**Comment by Mu-Gee** [comment]
> @Mu-Gee also not changed the db creds 🤣

I simply configured my side with the credentilals we are using for development thunder@localhost "thunder"
Don't be alarmed.

**Comment by Ndegwadavid** [comment]
🤣 i forgot thoough

**Pull request closed without merging**
