### PR TITLE
Modified hompage and additional new changes🥳 

### PR DESCRIPTION
**Pull request by Ndegwadavid**
added favicon and also a background simple interface.

Rethough of no complexity to be in place>>> 
Just simple for integration with the API for login and registration. functionality

### CODE REVIEW

**Comment by Ndegwadavid** [comment]
Also @Mu-Gee check on the static/css/styles.css its not present:
Tried creating it in root dir but not working,,
Same in root app not working.
💯 check on it ,,

**Comment by Ndegwadavid** [comment]
THis one is able to be merged: Thus merging it 👍🏿

**Comment by Mu-Gee** [comment]
> Also @Mu-Gee check on the static/css/styles.css its not present: Tried creating it in root dir but not working,, Same in root app not working. 💯 check on it ,,

Remember I told you I went on sabattical for a week or two, will be unavailable till weekend.

**Comment by Ndegwadavid** [comment]
No problem

**Pull request merged**
